### ISSUE TITLE
Relax `html2md-rs`?

### ISSUE THREAD

**Issue by getreu** [izyuumi/html2md-rs#18]
I like your parser, it has very few dependencies and a solid design.
I am currently testing it for [tp-note](https://github.com/getreu/tp-note). The use case: in case the clipboard contains HTML, a filter is needed to convert the input into CommonMark compliant Markdown. The input may contain complete HTML documents or just snippets, thus my previous [feature request](https://github.com/izyuumi/html2md-rs/issues/16).

Going through your Rustdoc, I discovered _panics if ...._ . Fortunately you offer _safe_ variants of panicking functions. To my knowledge, it is common practice that libraries must **never** panic. What is your use case?

Feature request:
Besides, my first tests indicate that your (safe) parser might be too strict for my use case. I probably would need a parser, which processes also imperfect/incorrect input. Even in cases where the input is not perfectly valid HTML5.

Once you publish 0.7 I test again how bad the copied HTML in the clipboard can be.

**Comment by izyuumi** [comment]
Would you share me an example of an input and output that you would want to see that will not return an error even with malformed HTML snippets?

Also, I have the panic there because I started the library with panics, and I wanted to make sure the project had backwards compatibility. Although, I guess I should make it so that users can opt in to use the panic-able version of the library.

**Comment by izyuumi** [comment]
I just marked `parse_html` as deprecated, and it will be removed in future versions (af0dfe943b60af08e36440bb5f14ef10074954de).

**Comment by getreu** [comment]
> Would you share me an example of inputs and outputs that you would want to see that will not return an error even with malformed HTML snippets?

I am not at the office today. Tomorrow I will send you some examples. 
[Tp-Note](https://github.com/getreu/tp-note) is processes to 2 kinds of HTML input:

1. Pipes from `curl`, example:

       curl http://blog.getreu.net/ | tpnote

2. HTML read from the system clipboard. This is probably the trickier part. I have no idea how well formed this HTML is. I will do some tests.

**Comment by getreu** [comment]
Below you find 3 examples of input data (originating from the clipboard):

[log.txt](https://github.com/izyuumi/html2md-rs/files/14785381/log.txt)
[log2.txt](https://github.com/izyuumi/html2md-rs/files/14785382/log2.txt)
[log3.txt](https://github.com/izyuumi/html2md-rs/files/14785383/log3.txt)



In the above examples, the `<html>` tag is omitted. When the input comes from `wget bahn.de`, it looks like

```html
<!DOCTYPE html>
<html class="no-js" lang="de">
  <head>
<script> window.bahn = window.bahn || { 'env': 'prd--default', 'cdsOrigin': 'https://www.bahn.de', 'site': 'next-bahn-de', 'lang': 'de', 'cookiePrefix': 'DB4-pb', 'pagetitle': 'DB Fahrplan, Auskunft, Tickets, informieren und buchen - Deutsche Bahn', 'pagename': 'startseite', 'section': 'Content', 'uuid': 'a5a66ce9-1eaa-41d7-87d4-1c9e52ea2bb1', 'hasWebComponent': false, 'abTestingService': { 'eventsActive': true, 'sdkKey': '2VwfARuJAzeMmnZHy6KR3' }, 'idm': { 'url': 'https://accounts.bahn.de', 'realm': '/auth/realms/db', 'active': true } } </script>


<title>DB Fahrplan, Auskunft, Tickets, informieren und buchen - Deutsche Bahn</title>
```

**Comment by izyuumi** [comment]
What do you expect the output from the parse be?

**Comment by getreu** [comment]
[log.txt.md](https://github.com/izyuumi/html2md-rs/files/14793297/log.txt.md)
[log2.txt.md](https://github.com/izyuumi/html2md-rs/files/14793298/log2.txt.md)
[log3.txt.md](https://github.com/izyuumi/html2md-rs/files/14793303/log3.txt.md)

**Comment by izyuumi** [comment]
How's something like this? ([36ec69b](https://github.com/izyuumi/html2md-rs/commit/36ec69bc5791df2e962a76b65a7b5038934f79a0))
Whatever unclosed tag will automatically be closed: [see tests](https://github.com/izyuumi/html2md-rs/blob/be05a437e484dbc0a927534d0975655dd8d1284d/tests/to_md_tests.rs#L189).

**Comment by getreu** [comment]
The examples I sent you describe my use case for the next feature of Tp-Note: _the user copies parts of the browser page into the clipboard as HTML. Tp-Note reads the clipboard and creates a new Markdown note._ This should make the browser plugin "copy as Markdown" obsolete. It tuns out, that the snippets in the clipboard are usually correct and well-formed HTML. So far my tests with Firefox under Linux.

**Comment by getreu** [comment]
Yes. when your library understands `html` and `meta` nodes, I'll test again. So far it looks good to me.
